spring:
  security:
    oauth2:
      client:
        registration:
          salesforce:
            client-id: <salesforce-client-id>
            client-secret: <salesforce-client-secret>
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: api
            client-name: Salesforce
        provider:
          salesforce:
            authorization-uri: https://login.salesforce.com/services/oauth2/authorize
            token-uri: https://login.salesforce.com/services/oauth2/token
            user-info-uri: https://login.salesforce.com/services/oauth2/userinfo
            user-name-attribute: username
